k3s-control-plane:
  description: "kubernetes control-plane"
  target_node: pve
  vmid: 201
  clone: "ubuntu-server-jammy"
  tags: "k8s,k8s-control-plane"
  ipconfig0: "ip=dhcp"
  resources:
    cpu: 2
    memory: 4096
    disk: 20G
k3s-worker-node-01:
  description: "kubernetes worker-node-01"
  target_node: pve
  vmid: 202
  clone: "ubuntu-server-jammy"
  tags: "k8s,k8s-worker-node"
  ipconfig0: "ip=dhcp"
  resources:
    cpu: 4
    memory: 8192
    disk: 20G
k3s-worker-node-02:
  description: "kubernetes worker-node-02"
  target_node: pve
  vmid: 203
  clone: "ubuntu-server-jammy"
  tags: "k8s,k8s-worker-node"
  ipconfig0: "ip=dhcp"
  resources:
    cpu: 4
    memory: 8192
    disk: 20G
