apiVersion: v2
name: prometheus-operator
description: A Helm chart for prometheus-operator, a declarative, GitOps continuous delivery tool for Kubernetes.
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 75.3.6
    repository: https://prometheus-community.github.io/helm-charts
