apiVersion: v2
name: grafana
description: A Helm chart for OpenTelemetry Operator.
type: application
version: 0.1.0
dependencies:
  - name: grafana
    version: 8.8.4
    repository: https://grafana.github.io/helm-charts
