enabled: true

namespace:
  values:
    namespace:
      name: ingress-system

ingress:
  source:
    url: https://github.com/kubernetes/ingress-nginx.git
    targetRevision: helm-chart-4.8.3
  values: {}
